[tool.ruff]
line-length = 120
target-version = "py39"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = ["ALL"]
extend-ignore = [
  # We don't use the following rules
  "COM812",  # (missing-trailing-comma) incompatible with ruff format
  "D203",  # (incorrect-blank-line-before-class) incompatible with D211: no-blank-line-before-class
  "D213",  # (multi-line-summary-second-line) incompatible with D212: multi-line-summary-first-line
  "SIM114",  # Combine if branches using logical or operator; this breaks mypy, so we disable it for now
  "TD",  # Linting TODOs; we dont need this
  "FIX",  # Disallow TODOs, FIXMEs, etc.; enforcing this is a bit too strict
  "E741",  # Ambiguous variable name, does not like quantum number 'l'
]
flake8-tidy-imports.ban-relative-imports = "all"
mccabe.max-complexity = 10

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true


[tool.mypy]
strict = true
disallow_untyped_decorators = false
ignore_missing_imports = true
